---
- name: Install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  vars: 
    java_name_package: openjdk-11-jdk
    user_name: tomcat
    group_name: tomcat
    user_home: /opt/tomcat
    user_shell: /bin/false
    tomcat_version:  "10.1.4"
    tomcat_version_major: "10"
    tomcat_service_name: tomcat.service     
  tasks:
    - name: install java 
      ansible.builtin.apt:
        name: "{{java_name_package}}"
        update_cache: yes
        state: present
    - name: create tomcat group
      ansible.builtin.group:
        name: "{{group_name}}"
        state: present    
    - name: create tomcat user
      ansible.builtin.user: 
        name: "{{user_name}}"
        create_home: yes
        group: "{{group_name}}"
        home: "{{user_home}}"
        shell: "{{user_shell}}"
        state: present   
    - name: extract tomcat 
      ansible.builtin.unarchive:
        src: "https://www-eu.apache.org/dist/tomcat/tomcat-{{tomcat_version_major}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz"
        remote_src: yes
        dest: "{{user_home}}"
    - name: create a symbolic link
      ansible.builtin.file:
        src: "{{user_home}}/apache-tomcat-{{tomcat_version}}"     
        dest: "{{user_home}}/latest"
        state: link
    - name: change permissions
      ansible.builtin.file:
        dest: "{user_home}"
        recurse: true
        owner: "{{user_name}}"
        group: "{{group_name}}"
        state: ddirectory
    - name: add execute permissions to shell files
      ansible.builtin.command: "sudo sh -c 'chmod +x {{user_home}}/latest/bin/*.sh' "
    - name: create a systemd unit files
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: "{{user_name}}"
        group: "{{group_name}}"
    - name: daemon reload and start tomcat
      ansible.builtin.systemd:
        name: "{{tomcat_service_name}}"
        daemon_reload: yes
        enabled: yes
        state: started      
    - name: copy user xml
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: "{{user_home}}/latest/conf/tomcat-users.xml" 
        owner: "{{user_name}}"
        group: "{{group_name}}"
    - name: copy manager app context files
      ansible.builtin.copy:
        src: context.xml
        dest: "{{user_home}}/latest/webapps/manager/META-INF/context.xml"
        owner: "{{user_name}}"
        group: "{{group_name}}"
    - name: copy host-manager to contextfile
      ansible.builtin.copy:
        src: hostmanager-context.xml
        dest: "{{user_home}}/latest/webapps/host-manager/META-INF/context.xml"
        owner: "{{user_name}}"
        group: "{{group_name}}"
    - name: restart tomcat
      ansible.builtin.systemd:
        name: "{{tomcat_service_name}}"
        state: started  